name: weather_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  animate_do: ^3.3.3
  dotenv: ^4.2.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  go_router: ^13.2.0
  google_fonts: ^6.1.0
  http: 1.1.0
  intl: ^0.19.0
  lottie: 2.7.0
  path_provider: ^2.1.2
  provider: ^6.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
